gnome.yelp(
  'mate-user-guide',
  sources: [
    'index.docbook',
    'legal.xml',
    'gosbasic.xml',
    'goscustdesk.xml',
    'goseditmainmenu.xml',
    'goscaja.xml',
    'gosoverview.xml',
    'gospanel.xml',
    'gosstartsession.xml',
    'gostools.xml',
    'gosdconf.xml',
    'gosdconfkeys.xml',
    'gosfeedback.xml',
    'glossary.xml',
  ],
)

install_subdir(
  'C/figures',
  install_dir: join_paths(get_option('datadir'), 'help', 'C', 'mate-user-guide'),
)
